name: bbqlagao_and_beefpares
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  flutter_riverpod: ^3.0.0
  crypto: ^3.0.6
  firebase_auth: ^6.0.2
  gradient_icon: ^2.0.9
  intl: ^0.20.2
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
